add_newline = true
follow_symlinks = true

# [ 󰣇 ](bg:#a3aed2 #2e3440 fg:#090c0c)\
format = """
[█](#28a0b8)\
$os\
[](bg:#393c63 fg:#28a0b8)\
$username\
[](bg:#2596be fg:#393c63)\
$directory\
[](fg:#2596be bg:#3b445e)\
$git_branch\
$git_status\
[](fg:#3b445e) \
$nodejs\
$rust\
$golang\
$php\
\n$character"""

[username]
format = '[ $user ]($style)'
disabled = false
show_always = true
style_user = "fg:#e3e5e5 bg:#393c63"

[os]
style = "fg:#2e3440 bg:#28a0b8"
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#2596be"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[os.symbols]
Arch = " "

[hostname]
ssh_only = false
disabled = true


[shell]
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3b445e"
format = '[[ $symbol $branch(:$remote_branch) ](fg:#769ff0 bg:#3b445e)]($style)'

[git_status]
style = "bg:#3b445e"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#3b445e)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
